services:
  - type: web
    name: simplebackend
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 7001
