services:
  - type: web
    name: express-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
